name: Redwood CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    #services:
      #postgres:
      #  image: postgres:16-bookworm
      #  env:
      #    POSTGRES_USER: redwood
      #    POSTGRES_PASSWORD: redwood
      #    POSTGRES_DB: redwood
      #  ports:
      #    - 5432:5432
      #  options: >-
      #    --health-cmd="pg_isready -U redwood"
      #    --health-interval=10s
      #    --health-timeout=5s
      #    --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      #- name: Install deps
      #  run: yarn install

      #- name: Generate Prisma client
      #  run: yarn rw prisma generate

      #- name: Run migrations
      #  run: yarn rw prisma migrate deploy
      #  env:
      #    DATABASE_URL: ${{ secrets.DATABASE_URL }}

      #- name: Project lint
      #  run: yarn rw lint

      #- name: Project types check
      #  run: yarn rw type-check

      #- name: Build app
      #  run: yarn rw build
      #  env:
      #    DATABASE_URL: ${{ secrets.DATABASE_URL }}

      #- name: Run tests
      #  run: yarn rw test
      #  env:
      #    TEST_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./devops/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./devops/terraform
        run: terraform apply -auto-approve

      - name: Get EC2 IP
        id: ip
        working-directory: ./devops/terraform
        run: echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_REDWOOD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.ip.outputs.ip }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${{ steps.ip.outputs.ip }}," \
            -u ubuntu \
            --private-key ~/.ssh/id_rsa \
            ansible/playbook.yml

      - name: Show URL
        run: echo "App running at http://${{ steps.ip.outputs.ip }}"
